spring.application.name=product
server.port=8084

spring.cloud.gcp.firestore.enabled=true
spring.cloud.gcp.project-id=my-project-chat-ai-487408
spring.cloud.gcp.credentials.location=file:/home/shivam-sharma/.gcp/my-project-chat-ai-487408-5604b2cd4107.json