spring.application.name=product
server.port=8084

# Firestore
spring.cloud.gcp.firestore.enabled=true
# spring.cloud.gcp.project-id=your-gcp-project
# For local emulator: spring.cloud.gcp.firestore.emulator.enabled=true

# Pub/Sub - for outbox publisher
# spring.cloud.gcp.project-id=your-gcp-project
gcp.firestore.project-id=my-project-chat-ai-487408
gcp.firestore.credentials-path=/home/shivam-sharma/.gcp/my-project-chat-ai-487408-5604b2cd4107.json